version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports: 
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  prometheus:
    image: prom/prometheus
    volumes: 
      - ./observability/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports: 
      - 9090:9090

  collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./observability/collector-gateway.yml:/conf/collector-config.yaml
    ports:
      - "8888:8888"   # metrics data exposed to prometheus
      - "8889:8889"   # Prometheus exporter metrics
      - "4318:4318"   # OTLP HTTP receiver

    depends_on:
      - jaeger